### PR TITLE
refactor main.js and issue.js to use ES6 template literals

### PR DESCRIPTION
**Pull request by iamwebwiz**
- refactor `js/main.js` code to use ES6 template literals instead of string concatenation
- refactor `js/issue.js` code to use ES6 template literals instead of string concatenation

### CODE REVIEW

**Comment by Itope84** [comment]
I don't know if this is fine, since one of the major concerns is supporting as many devices as possible.

**Comment by iamwebwiz** [comment]
I see. I just think tech isn't going any backward and we shouldn't either. Most modern browsers support template literals already.

**Comment by FredrikAugust** [comment]
Thanks a lot man! :)

**Comment by iamwebwiz** [comment]
> Thanks a lot! :)

My pleasure! :fire:

**Pull request merged**
